target:
  plat_info: ~/power/pixel6/workload-processor/assets/p6-platform-info.yml
  target_conf: ~/tools/lisa/target_conf_p6.yml
  clusters: {
      'little': [0, 1, 2, 3],
      'mid': [4, 5],
      'big': [6, 7],
  }
host:
  adb_host: 127.0.0.1
  adb_port: 5037
device:
  lisa_module_path: /data/local/lisa.ko
processor:
  important_tasks:
    jankbench: [
      'RenderThread', 'droid.benchmark', 'surfaceflinger', 'decon0_kthread',
    ]
    geekbench: [
      'AsyncTask #1', 'labs.geekbench5', 'surfaceflinger',
    ]
    speedometer: [
      'CrRendererMain', 'ThreadPoolForeg', '.android.chrome', 'CrGpuMain', 'Compositor',
      'Chrome_IOThread', 'surfaceflinger', 'RenderThread',
    ]
    drarm: [
      'UnityMain', 'UnityGfxDeviceW', 'Thread-7', 'Thread-6', 'Thread-5', 'Thread-4',
      'surfaceflinger', 'mali-cmar-backe', 'mali_jd_thread', 'writer', 'FastMixer',
      'RenderEngine', 'Audio Mixer Thr', 'UnityChoreograp',
    ]
    fortnite: [
      'GameThread', 'RHIThread', 'RenderThread 0', 'AudioMi-nder(1)', 'Foregro-rker #1',
      'Foregro-rker #0', 'Backgro-rker #2', 'Backgro-rker #3', 'mali-cmar-backe',
      'FastMixer', 'surfaceflinger', 'writer', 'ElectraPlayer::', 'MediaCodec_loop',
      'RenderEngine', 'mali-compiler', 'mali_jd_thread', 'oid.aac.decoder'
    ]
